version: '3.4'

services:
  chatapp_api:
    container_name: ChatApp_API
    image: chatapp_api
    build:
      context: .
      dockerfile: ChatApp.API/Dockerfile
    depends_on:
        - postgres
    ports:
        - "5000:5000"
    environment:
        ASPNETCORE_URLS: "http://+:5000"
        ASPNETCORE_ENVIRONMENT: "Development"
    networks:
        - chatapp-network

  chatapp_client:
    container_name: ChatApp_Client
    image: chatapp_client
    build:
        context: .
        dockerfile: ChatApp.Client/Dockerfile
    depends_on:
        - postgres
        - chatapp_api
    ports:
        - "4000:4000"
    environment:
        ASPNETCORE_URLS: "http://+:4000"
        ASPNETCORE_ENVIRONMENT: "Development"
    networks:
        - chatapp-network

  postgres:
    container_name: chatapp_postgres
    image: postgres:latest
    restart: on-failure:3
    ports:
        - "5432:5432"
    volumes:
        - postgres_chatapp_data:/var/lib/postgresql/data/
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: chatapp
        PGDATA: /var/lib/postgresql/data/
    networks:
        - chatapp-network

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: on-failure:3
    depends_on:
        - postgres
    environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        PGADMIN_LISTEN_PORT: "5050"
    ports:
      - "5050:5050"
    networks:
        - chatapp-network

volumes:
    postgres_chatapp_data:
    
networks:
    chatapp-network:
        driver: bridge