version: '3.4'

services:
  chatapp:
    image: ${DOCKER_REGISTRY-}chatapp
    build:
      context: .
      dockerfile: ChatApp/Dockerfile
    depends_on:
        - postgres
    ports:
        - "5000:80"
    networks:
        - "chatapp-network"

  postgres:
    container_name: chatapp_postgres
    image: postgres:latest
    restart: on-failure:3
    ports:
        - "5432:5432"
    networks:
        - "chatapp-network"
    volumes:
        - postgres_chatapp_data:/var/lib/postgresql/data/
    environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_DB: chatapp
        PGDATA: /var/lib/postgresql/data/

networks:
    chatapp-network:
        driver: bridge

volumes:
    postgres_chatapp_data:    